# Generated by Django 5.0.4 on 2024-05-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ndviimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndviimage',
            name='image',
            field=models.FileField(upload_to='ndvi_images/'),
        ),
    ]
