# Generated by Django 5.0.4 on 2024-05-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ndviimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndviimage',
            name='image',
            field=models.ImageField(upload_to='ndvi_images/'),
        ),
    ]
