# Generated by Django 5.0.4 on 2024-06-13 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ndmivalue_delete_smivalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetrologicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_data', models.FloatField(null=True)),
                ('humidity_data', models.FloatField(null=True)),
                ('rainfall_data', models.FloatField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='app.customer')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='app.polygonmodel')),
            ],
        ),
    ]
