# Generated by Django 5.0.4 on 2024-06-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_metrologicaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrologicaldata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
