# Generated by Django 5.0.4 on 2024-06-14 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_metrologicaldata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ndviimage',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ndviimage',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='ndvivalue',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ndvivalue',
            name='polygon',
        ),
        migrations.CreateModel(
            name='LANDSAT8DATASETValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ndvi_value', models.FloatField(null=True)),
                ('ndwi_value', models.FloatField(null=True)),
                ('ndmi_value', models.FloatField(null=True)),
                ('evi_value', models.FloatField(null=True)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='landsat8_dataset_values', to='app.customer')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landsat8_dataset_values', to='app.polygonmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LANDSAT8Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi_image', models.ImageField(upload_to='landsat8/ndvi_images/')),
                ('ndwi_image', models.ImageField(upload_to='landsat8/ndwi_images/')),
                ('ndmi_image', models.ImageField(upload_to='landsat8/ndmi_images/')),
                ('evi_image', models.ImageField(upload_to='landsat8/evi_images/')),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landsat8_images', to='app.customer')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landsat8_images', to='app.polygonmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LANDSAT9DATASETValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ndvi_value', models.FloatField(null=True)),
                ('ndwi_value', models.FloatField(null=True)),
                ('ndmi_value', models.FloatField(null=True)),
                ('evi_value', models.FloatField(null=True)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='landsat9_dataset_values', to='app.customer')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landsat9_dataset_values', to='app.polygonmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LANDSAT9Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi_image', models.ImageField(upload_to='landsat9/ndvi_images/')),
                ('ndwi_image', models.ImageField(upload_to='landsat9/ndwi_images/')),
                ('ndmi_image', models.ImageField(upload_to='landsat9/ndmi_images/')),
                ('evi_image', models.ImageField(upload_to='landsat9/evi_images/')),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landsat9_images', to='app.customer')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landsat9_images', to='app.polygonmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MODISDATASETValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ndvi_value', models.FloatField(null=True)),
                ('ndwi_value', models.FloatField(null=True)),
                ('ndmi_value', models.FloatField(null=True)),
                ('evi_value', models.FloatField(null=True)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='modis_dataset_values', to='app.customer')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modis_dataset_values', to='app.polygonmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MODISImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi_image', models.ImageField(upload_to='modis/ndvi_images/')),
                ('ndwi_image', models.ImageField(upload_to='modis/ndwi_images/')),
                ('ndmi_image', models.ImageField(upload_to='modis/ndmi_images/')),
                ('evi_image', models.ImageField(upload_to='modis/evi_images/')),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modis_images', to='app.customer')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modis_images', to='app.polygonmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SENTINELDATASETValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ndvi_value', models.FloatField(null=True)),
                ('ndwi_value', models.FloatField(null=True)),
                ('ndmi_value', models.FloatField(null=True)),
                ('evi_value', models.FloatField(null=True)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sentinel_dataset_values', to='app.customer')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentinel_dataset_values', to='app.polygonmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SENTINELImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi_image', models.ImageField(upload_to='sentinel/ndvi_images/')),
                ('ndwi_image', models.ImageField(upload_to='sentinel/ndwi_images/')),
                ('ndmi_image', models.ImageField(upload_to='sentinel/ndmi_images/')),
                ('evi_image', models.ImageField(upload_to='sentinel/evi_images/')),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentinel_images', to='app.customer')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentinel_images', to='app.polygonmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='NDMIValue',
        ),
        migrations.DeleteModel(
            name='NDVIIMAGE',
        ),
        migrations.DeleteModel(
            name='NDVIValue',
        ),
    ]
